---
language: scala
script: "sbt coveralls test"
scala:
- 2.9.2
before_script:
 - "echo JAVA_HOME $JAVA_HOME"
 - "echo 'which java' `which java`"
 - "echo JAVA_OPTS $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
before_install:
  - sudo apt-get update -qq
  - wget http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz
  - tar zxf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure --prefix=/usr
  - make
  - sudo make install
